### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by mabaisen** [FRBs/sigpyproc3#32]
When i use "PFITSReader" to read a fits file, then use "read_block" get the data, i have the problem:

Traceback (most recent call last):
  File "/home/mbs/Desktop/mycode/ASTROSOFT/sigpyproc3/read_fil.py", line 13, in <module>
    c = fil.read_block(start=1000, nsamps=2000)
  File "/home/mbs/Desktop/mycode/ASTROSOFT/sigpyproc3/sigpyproc/readers.py", line 208, in read_block
    data = self._fitsfile.read_subints(startsub, nsubs)
  File "/home/mbs/Desktop/mycode/ASTROSOFT/sigpyproc3/sigpyproc/io/pfits.py", line 412, in read_subints
    sdata = self.read_subint_pol(
  File "/home/mbs/Desktop/mycode/ASTROSOFT/sigpyproc3/sigpyproc/io/pfits.py", line 464, in read_subint_pol
    return data
UnboundLocalError: local variable 'data' referenced before assignment

How can i fix it.

**Comment by pravirkr** [comment]
It looks like the `poln_state` is not included in `read_subint_pol` yet. I should raise the correct exception in the function.

The `PFITSReader` is still experimental and does not support all types of PSRFITS files as of yet.

**Comment by saikumar781588** [comment]
i got same error while doing the qswatmod2 in qgis . please help me how to fix this problem

**Comment by mabaisen** [comment]
> i got same error while doing the qswatmod2 in qgis . please help me how to fix this problem

Sorry, I haven't been doing this task for a long time

**Comment by saikumar781588** [comment]
okay sir thankyou
